ahickco/greatwar/postcards/urls.py
from django.conf.urls.defaults import patterns, include

urlpatterns = patterns('greatwar.postcards.views',
    (r'^$', 'postcards'),
#    (r'^poet$', 'poets'),
#    (r'^poet/(?P<letter>[A-Z]*)$', 'poets_by_firstletter'),                       
#    (r'^poet/(?P<name>.*)$', 'poet_list'),
#    (r'^(?P<doc_id>[^/]+)$', 'book_toc'),
#    (r'^(?P<doc_id>[^/]+)/(?P<div_id>[a-zA-Z_0-9]+)$', 'div'),
)
 

greatWar/edc/urls.py
from django.conf.urls.defaults import *
from edc import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
	(r'^site_media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': '/home/html/greatWar/templates/'}),
	(r'^about/$', 'edc.search.views.about'),
	(r'^credits/$', 'edc.search.views.credits'),
	(r'^poetrysearch/advanced/$', 'edc.search.views.advancedSearch'),
	(r'^poetry/volume_browse/$', 'edc.search.views.volume_browse'),
	(r'^poetry/volume/(?P<volfile>\w+)/$', 'edc.search.views.volumeContent'),
	(r'^poetry/front/(?P<div_id>\w+)/$', 'edc.search.views.front_detail'),
	(r'^poetry/(?P<parent_type>\w+)/(?P<poem_id>\w+)/$', 'edc.search.views.poem_detail'),
	(r'^poetry/poem/(?P<poem_id>\w+)/$', 'edc.search.views.poem_detail'),
	(r'^$', 'edc.search.views.opening_page'),
	(r'^postcards$', 'edc.search.views.underconstruction'),
	(r'^links$', 'edc.search.views.underconstruction'),
        (r'^poetry/Poet_browse/$', 'edc.search.views.underconstruction'),
)

greatwar/postcards/urls.py
from django.conf.urls import url
from django.views.decorators.cache import cache_page

from greatwar.postcards import views

urlpatterns = [
    url(r'^$', views.browse, name='browse'),
    url(r'^about/$', views.summary, name='index'),
    url(r'^categories/(?P<subject>.*)$', views.browse, name='browse'),
    url(r'^(?P<pid>[^/]+)$', views.view_postcard, name='card'),
    url(r'^large/(?P<pid>[^/]+)$', views.view_postcard_large, name='card-large'),
    url(r'^(?P<pid>[^/]+)/thumbnail/$', views.postcard_image, {'size': 'thumbnail'}, name='img-thumb'),
    url(r'^(?P<pid>[^/]+)/medium/$', views.postcard_image, {'size': 'medium'}, name='img-medium'),
    url(r'^(?P<pid>[^/]+)/large/$', views.postcard_image, {'size': 'large'}, name='img-large'),
    url(r'^search/$', views.search, name='search'),
]

greatwar/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from greatwar import views


admin.autodiscover()

urlpatterns = [
    # Example:
    url(r'^$', views.index, name="index"),
    url(r'^$', views.index, name="site-index"), # required by eultheme
    url(r'^about/$', views.about, name="about"),
    url(r'^links/$', views.links, name="links"),
    url(r'^credits/$', views.credits, name="credits"),
    url(r'^poetry/', include('greatwar.poetry.urls', namespace='poetry')),
    url(r'^postcards/', include('greatwar.postcards.urls', namespace='postcards')),
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # django admin, for downtime/banners
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEV_ENV:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ahickco/greatwar/postcards/models.py
#from django.db import models
from django.conf import settings
from eulcore import xmlmap
from eulcore.xmlmap.teimap import TeiFigure
from eulcore.existdb.query import QuerySet
from eulcore.django.existdb.db import ExistDB
from eulcore.xmlmap.core import XmlObject #, XPathString
from eulcore.django.existdb.models import XmlModel


# TEI postcard model
#class Postcard(TeiFigure):
#     objects = QuerySet(model=TeiFigure, xpath="/TEI.2", using=ExistDB()
#                        collection=settings.EXISTDB_ROOT_COLLECTION)

class PostcardThumb(TeiFigure):
     card = xmlmap.StringField("head")
     entity = xmlmap.StringField("@entity")
     ana = xmlmap.StringField("@ana")
     description = xmlmap.StringField("figDesc")
     objects = QuerySet(model=TeiFigure, xpath="//figure", using=ExistDB()
                        collection=localsettings.EXISTDB_ROOT_COLLECTION)
PostcardThumb.objects.model = PostcardThumb

greatwar-django/tags/release-1.0.0/greatwar/postcards/forms.py
from django import forms

class SearchForm(forms.Form):
    #keyword = forms.CharField(help_text='Search anywhere in postcard metadata')
    title = forms.CharField(required=False)
    description = forms.CharField(required=False)

    def clean(self):
        """Custom form validation."""
        cleaned_data = self.cleaned_data

        title = cleaned_data.get('title')
        description = cleaned_data.get('description')

        #Validate at least one term has been entered
        if not title and not description:
            del cleaned_data['title']
            del cleaned_data['description']

            raise forms.ValidationError("Please enter search terms for title or description")

        return cleaned_data

greatWar/edc/search/views.py
from django.http import HttpResponse
from django import forms
from django.shortcuts import render_to_response
from existdb.db import ExistDB, ResultPaginator,ExistDBException
from edc.search.forms import SimpleSearchForm, ExtendedSearchForm, SearchFormSet,BasicSearchForm,BasicSearchBox,AdvancedSearchBox
from edc.search.models import CodeBookQueryResult, BookStoreQueryResult,BookQueryResult,BookResult,BookDetailResult,BookDetailQueryResult,BriefPoemList,FullPoemList,BriefVolList,BriefPoemList1,DetailPoem,VolumeContent,FrontContent
from django.forms.formsets import BaseFormSet, ValidationError
from django.conf import settings

PER_PAGE = 10

#display/process basic search from
def index(request):
    return renderForm(SimpleSearchForm, request, 'search/basic.xhtml', 'search')
    
def index_test(request):
    return renderForm_test(BasicSearchForm, request, 'search/basic_test.xhtml', 'search')
    
    
def book_detail(request,book_id):
    db = ExistDB(resultType=BookDetailQueryResult)
    results = db.query(xQry_by_id(book_id))
    return  render_to_response('search/show_test.xhtml', {
                        'data': results.books,
                        'book_id':        book_id,
                        'app_root':         request.META['SCRIPT_NAME'],
                        'previous_page':    request.GET.get('search_type', None),
                        'previous_data':    request.META['QUERY_STRING']
                        })
          
def poem_detail(request, parent_type,poem_id):
    db = ExistDB(resultType=DetailPoem)
    xQry = xQry_by_id1(poem_id)
    results = db.query(xQry)
    #assert False
    return  render_to_response('poetry/view.xhtml', {
                        'fullPoem': results,
                            'basicSearchBox': BasicSearchBox()
                        })
                  
def extended(request):
    return renderForm(SearchFormSet, request, 'search/extended.xhtml', 'extended')

def study(request, book_id):
    db = ExistDB(resultType=CodeBookQueryResult)
    results = db.query(xQry_by_id(survey_id))

    return  render_to_response('search/show.xhtml', {
                        'data': results.codeBooks,
                        'survey_id':        survey_id,
                        'app_root':         request.META['SCRIPT_NAME'],
                        'previous_page':    request.GET.get('search_type', None),
                        'previous_data':    request.META['QUERY_STRING']
                        })

def download(request, survey_id):
    db = ExistDB(resultType=CodeBookQueryResult)
    results = db.query(xQry_by_id(survey_id))

    return  render_to_response('search/download.xhtml', {
                        'data': results.codeBooks,
                        'survey_id':        survey_id,
                        'app_root':         request.META['SCRIPT_NAME'],
                        'previous_page':    request.GET.get('search_type', None ),
                        'previous_data':    request.META['QUERY_STRING']
                        })

def widget(request, type='simple'):
    if type == 'extended':
        return extended(request)
    else:
        return index(request)

#HELPER METHODS
def xQry(filter_list, condition='and', collection=settings.EXISTDB_ROOT_COLLECTION):

    filters = []
    terms   = []
    for f in filter_list:
        if ('field' not in f):
            key = 'entireDoc'
        else:
            key = f['field']

        if f['term'] != '':
            search_filter = {}
            search_filter['title']      = "(docDscr/citation/titlStmt/titl &= '%(term)s' or docDscr/citation/titlStmt/IDNo = '%(term)s')" % {'term': f['term']}
            search_filter['abstract']   = "stdyDscr/stdyInfo/abstract &= '%(term)s'" % {'term': f['term']}
            search_filter['pi']         = "stdyDscr/citation/rspStmt/AuthEnty &= '%(term)s'" % {'term': f['term']}
            search_filter['subject']    = "stdyDscr/stdyInfo/subject/keyword &= '%(term)s'" % {'term': f['term']}
            search_filter['geoCover']   = "stdyDscr/stdyInfo/sumDscr/geogCover &= '%(term)s'" % {'term': f['term']}
            search_filter['timePrd']    = "stdyDscr/stdyInfo/sumDscr/timePrd/@date &= '%(term)s'" % {'term': f['term']}
            search_filter['entireDoc']   = ". &= '%(term)s'" % {'term': f['term']}

            filters.append(search_filter[key])
            terms.append(f['term'])

   # import module namespace date="http://www.library.emory.edu/xquery/date" at
    #          "xmldb:exist:///db/xquery-modules/date.xqm";
	xqry = '''for $a in collection("/db%(collection)s")/codeBook[%(filter)s][.|='%(terms)s']
              let $matchcount := text:match-count($a)
              order by $a/docDscr/citation/titlStmt/titl
              return <codeBook>{$a/*} <hits>{$matchcount}</hits></codeBook>'''
    
    return xqry % {'filter': condition.join(filters), 'terms': ' '.join(terms), 'collection': collection}
    
    
    
def xQry2(qry_data, collection=settings.EXISTDB_ROOT_COLLECTION):
	filter1=[]
	filter2=[]
	filter3=[]
	filter4=["@type=\"poem\""]
	filler1=""
	filler2=""
	filler3=""
	filler4=""
	
	if 'author' in qry_data:
		if qry_data['author']!='':
			filter1.append("docAuthor&=\"%(term)s\"" % {'term':qry_data['author']})
			filter4.append("docAuthor&=\"%(term)s\"" % {'term':qry_data['author']})
	if 'date' in qry_data:
		if qry_data['date']!='':
			filter1.append(".//bibl/date='%(term)s'" % {'term':qry_data['date']})
			filter3.append(".//bibl/date='%(term)s'" % {'term':qry_data['date']})
		
	if 'title' in qry_data:
		if qry_data['title']!='':
			filter2.append("head&=\"%(term)s\"" % {'term':qry_data['title']})
	if 'term' in qry_data:
		if qry_data['term']!='':
			filter2.append(".//l&=\"%(term)s\"" % {'term':qry_data['term']});
		
	if filter1:
		filler1="[%(term)s]" % {'term':' and '.join(filter1)}
	if filter2:
		filler2="where $poem[%(term)s]" % {'term':' and '.join(filter2)}
	if filter3:
		filler3="[%(term)s]" % {'term':' and '.join(filter3)}
	filler4="[%(term)s]" % {'term':' and '.join(filter4)}
	
	xqry = '''for $vol in collection("/db%(collection)s")/TEI.2
			return
			if ($vol//div/@type='Poetry')
			then for $poem in $vol//div%(filler1)s//div[@type="Poem"]
					%(filler2)s
					return <briefPoem><id>{data($poem/@id)}</id><author>{data($vol//div/docAuthor)}</author><title>{data($poem/head)}</title></briefPoem>
			else for $poem in $vol%(filler3)s//div%(filler4)s
					%(filler2)s
					return <briefPoem><id>{data($poem/@id)}</id><author>{data($poem/docAuthor)}</author><title>{data($poem/head)}</title></briefPoem>'''
	return xqry % {'collection': collection,'filler1':filler1,'filler2':filler2,'filler3':filler3,'filler4':filler4}
    
    
def xQry4(qry_data, collection=settings.EXISTDB_ROOT_COLLECTION):
	filter1=[]
	filter2=[]
	filter3=[]
	filter4=["@type=\"poem\""]
	filler1=""
	filler2=""
	filler3=""
	filler4=""
	
	if 'author' in qry_data:
		if qry_data['author']!='':
			filter1.append("docAuthor&=\"%(term)s\"" % {'term':qry_data['author']})
			filter4.append("docAuthor&=\"%(term)s\"" % {'term':qry_data['author']})
	if 'date' in qry_data:
		if qry_data['date']!='':
			filter1.append(".//bibl/date='%(term)s'" % {'term':qry_data['date']})
			filter3.append(".//bibl/date='%(term)s'" % {'term':qry_data['date']})
		
	if 'title' in qry_data:
		if qry_data['title']!='':
			filter2.append("head&=\"%(term)s\"" % {'term':qry_data['title']})
	if 'term' in qry_data:
		if qry_data['term']!='':
			filter2.append(".//l&=\"%(term)s\"" % {'term':qry_data['term']});
		
	if filter1:
		filler1="[%(term)s]" % {'term':' and '.join(filter1)}
	if filter2:
		filler2="where $poem[%(term)s]" % {'term':' and '.join(filter2)}
	if filter3:
		filler3="[%(term)s]" % {'term':' and '.join(filter3)}
	filler4="[%(term)s]" % {'term':' and '.join(filter4)}
	
	xqry = '''for $vol in collection("/db%(collection)s")/TEI.2
			return
			if ($vol//div/@type='Poetry')
			then for $poem in $vol//div%(filler1)s//div[@type="Poem"]
					%(filler2)s
					return <div>{$poem/*}<docAuthor>{data($vol//div/docAuthor)}</docAuthor></div>
			else for $poem in $vol%(filler3)s//div%(filler4)s
					%(filler2)s
					return $poem'''
	return xqry % {'collection': collection,'filler1':filler1,'filler2':filler2,'filler3':filler3,'filler4':filler4}

def xQry1(filter_list, condition='and', collection=settings.EXISTDB_ROOT_COLLECTION):

    filters = []
    terms   = []
    for f in filter_list:
        if ('field' not in f):
            key = 'entireDoc'
        else:
            key = f['field']
	xqry = '''for $a in collection("/db%(collection)s")/bookstore/book[title&='%(searchterm)s'] 
              return <book>{$a/*}</book>'''
    return xqry % {'collection': collection,'searchterm':f['term']}

def xQry_by_id(id, collection=settings.EXISTDB_ROOT_COLLECTION):
	#'''import module namespace date="http://www.library.emory.edu/xquery/date" at
	#      "xmldb:exist:///db/xquery-modules/date.xqm";
	return '''for $vol in collection("/db%(collection)s")/TEI.2
			let $poem := $vol//div[@id='%(id)s']
			where  $vol//div[@id='%(id)s']
			return <fullPoem><title>{data($vol/teiHeader/fileDesc/titleStmt/title)}</title>
			<editor>{data($vol/teiHeader/fileDesc/titleStmt/editor)}</editor>
			<ptitle>{data($vol//sourceDesc//bibl/title)}</ptitle>
			<peditor>{data($vol//sourceDesc//bibl/editor)}</peditor>
			<pplace>{data($vol//sourceDesc//bibl/pubPlace)}</pplace>
			<publisher>{data($vol//sourceDesc//bibl/publisher)}</publisher>
			<pdate>{data($vol//sourceDesc//bibl/date)}</pdate>
			{$poem/*}</fullPoem>''' % {'id': id, 'collection': collection}

def xQry_by_id1(id, collection=settings.EXISTDB_ROOT_COLLECTION):
	#'''import module namespace date="http://www.library.emory.edu/xquery/date" at
	#      "xmldb:exist:///db/xquery-modules/date.xqm";
		#	<xmlfilename>{substring-after(substring-before(substring-after(document-uri($doc),static-base-uri()),'.'),'/')}</xmlfilename>
	return '''for $doc in collection("/db%(collection)s")[TEI.2]

templates/postcards/_thumbnail_view.html
{# display a postcard with thumbnail and label, linking to main postcard record #}
<p class="thumbnail">
  <a href="{% url 'postcards:card' pid=postcard.pid %}" class="img">
  <img class="thumbnail" alt="postcard thumbnail"
      src="{{ postcard.thumbnail_url }}" />
  </a>
  <br/>
   {{ postcard.label }}
</p>

templates/postcards/browse.html
{% extends "postcards/postcard_base.html" %}
{% block page_subtitle %} Browse postcards {% endblock %}

{% block content %}
{% if postcards_paginated.paginator.count %}
    <p>Displaying {{ postcards_paginated.start_index }} - {{ postcards_paginated.end_index }} of {{ postcards_paginated.paginator.count }} postcard{{ postcards_paginated.paginator.count|pluralize }}.</p>
{# % assert False % #}
{% endif %}
{% if subject %}
    <p>Subject is {{subject}}.</p>
{% endif %}

{% if postcards_paginated %}
   {% for postcard in postcards_paginated.object_list %}
     {% include 'postcards/_thumbnail_view.html' %}
   {% endfor %}
{% endif %}


<table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td width="150">
    &nbsp;
    {% if postcards_paginated.has_previous %}
        <a href="?page={{ postcards_paginated.previous_page_number }}{% if subject %}&subject={{subject}}{% endif %}">[ &nbsp;&lt;&lt; Previous &nbsp;]</a>
    {% endif %}
    </td>
    
     <td align="center">
      [&nbsp; 
      {% for current_page in postcards_paginated.paginator.page_range %}
        {% if postcards_paginated.number == current_page %}
          &nbsp;{{ current_page }}&nbsp;
        {% else %}
          <a href="?page={{ current_page }}{% if subject %}&subject={{ subject }}{% endif %}">&nbsp;{{ current_page }}&nbsp;</a>
        {% endif %}
      {% endfor %}
      &nbsp;]
     </td>
  
      <td width="150" align="right">
      {% if postcards_paginated.has_next %}
          <a href="?page={{ postcards_paginated.next_page_number }}{% if subject %}&subject={{subject}}{% endif %}">[ &nbsp;Next &gt;&gt;&nbsp; ]</a>
      {% endif %}
      &nbsp;
      </td>
  </tr>
</table>
{% endblock %}

templates/postcards/index.html
{% extends "postcards/postcard_base.html" %}


{% block page_subtitle %} Introduction {% endblock %}
{% block page-head %}
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
{% endblock %}
{% block postcard %}
<div class="random_postcard">
    {% if count > 0 %}
        {% with postcards|random as postcard %}
            {% include 'postcards/_thumbnail_view.html' %}
         {% endwith %}
{% endif %}
    </div>
    {% endblock %}

{% block content %}
<p>For more information about the postcards, read <a href="{% url 'about' %}">about
this project</a>.</p>
<p>
There are several different ways to view the postcards:
<ul>
<li><a href="{% url 'postcards:browse' %}">Browse</a> - browse through all <b>{{count}}</b> postcards<br>
View thumbnails with titles, or thumbnails with a brief description<br>
(not advisable for slow connections) </li>


<li>Browse by category
<div class="categories">
  {% for group in categories %}
 	  <a onClick="$('#{{ group.type|slugify }}').toggle()">
          <h4 id="category-label" class ="toggle">{{ group.type }}</h4></a>
     <ul id="{{ group.type|slugify }}" class="category">
          {% for interp in group.interp %}
            <li><a href="{% url 'postcards:browse' %}?subject={{ group.type }}: {{ interp.value }}">{{ interp.value }}</a></li>
          {% endfor %}
      </ul>

   {% endfor %}
</div>
</li>
<li><a href="{% url 'postcards:search' %}">Search</a> the postcards by keyword, title, description, and category
</li>
</ul>

<p>Images of the postcards are available in three sizes:</p>
<ul>
<li>Thumbnail - browse pages & search results<br>
(may be viewed with titles only, or with brief descriptions)
</li>
<li>realsize - view an individual postcard at approximately actual size with full details</li>
<li>doublesize - from the realsize view, select an enlarged individual postcard view</li>
</ul>
{% endblock %}

templates/postcards/postcard_base.html
{% extends "base.html" %}
{% block pagetitle %}
| Postcards | {% block page_subtitle %}  {% endblock %}
{% endblock %}

{% block section_nav %}
<h3>Navigation</h3>
  <p>
   <a href="{% url 'postcards:browse' %}">Browse Postcards</a><br>
   <a href="{% url 'postcards:index' %}">Postcards Home</a><br>
   <a href="{% url 'postcards:search' %}">Advanced Search</a>
  </p>
{% endblock %}

templates/postcards/search.html
{% extends "postcards/postcard_base.html" %}
{% block page_subtitle %} Search {% endblock %}

{% block content %}

<h2>Search for postcards.</h2>
<form method="get" action="{% url 'postcards:search' %}">
    <table>
    {{ search.as_table }}
    </table>
    <input type="submit" value="Search" />
</form>

<hr/>
{% if server_error %}{{ server_error }}{% endif %}

{% if search.is_valid %} {# check if there was a search; empty paginator seems to evaluate as false in current djangos #}
  <br />
  Displaying {{ postcards_paginated.start_index }} - {{ postcards_paginated.end_index }} of {{ postcards_paginated.paginator.count }} total records.
  <br /><br />

  <table class="thumbnail">
      {% for postcard in postcards_paginated.object_list %}
      <tr>
         <td>
           <a href="{% url 'postcards:card' pid=postcard.pid %}" class="img">
              <img class="thumbnail" alt="postcard thumbnail"
                  src="{% url 'postcards:img-thumb' pid=postcard.pid %}" />
           </a>
         </td>
         <td class="description">
             {# FIXME: duplicates display logic from single-postcard template #}
             <h4>{{ postcard.dc.content.title }}</h4>
             <p>{{ postcard.dc.content.description }}</p>
             <h5>Categories:</h5>
             <ul>
                  {% for subject in postcard.dc.content.subject_list %}
                   <li>{{ subject }}</li>
                  {% endfor %}
             </ul>
         </td>
      </tr>
      {% empty %}
        <tr><td>no results</td></tr>
      {% endfor %}
  </table>

    <table width="100%" border="0" cellpadding="0" cellspacing="0">
    <tr>
      <td colspan="3">&nbsp;</td>
    </tr>
    <tr>
      <td width="150">
      &nbsp;
      {% if postcards_paginated.has_previous %}
          <a href="?page={{ postcards_paginated.previous_page_number }}&keyword={{keyword}}&title={{title}}&author={{author}}">[ &nbsp;&lt;&lt; Previous &nbsp;]</a>
      {% endif %}
      </td>

       <td align="center">
        [&nbsp;
        {% for current_page in postcards_paginated.paginator.page_range %}
          {% if postcards_paginated.number == current_page %}
            &nbsp;{{ current_page }}&nbsp;
          {% else %}
            <a href="?page={{ current_page }}&title={{title}}&description={{description}}">&nbsp;{{ current_page }}&nbsp;</a>
          {% endif %}
        {% endfor %}
        &nbsp;]
       </td>

        <td width="150" align="right">
        {% if postcards_paginated.has_next %}
            <a href="?page={{ postcards_paginated.next_page_number }}&title={{title}}&description={{description}}">[ &nbsp;Next &gt;&gt;&nbsp; ]</a>
        {% endif %}
        &nbsp;
        </td>
    </tr>
    </table>

{% endif %}

{% endblock %}

templates/postcards/view_postcard.html
{% extends "postcards/postcard_base.html" %}

{% block page-head %}
  {{block.super}}
  {# Dublin Core metadata for this postcard #}
  {% with card.dc.content as dc %}{% include '_dc_meta.html' %}{% endwith %}
{% endblock %}

{% block page_subtitle %} {{head}} {{card.label}} {% endblock %}

{% block content %}
<p><a href="{% url 'postcards:card-large' pid=card.pid %}">View larger image</a></p>
<table>
  <tr>
    <td>
        <img src="{{ card.medium_img_url }}" />
    </td>  <!-- put link to 2x image here -->
    <td class="description">
        <h4>{{card.label}}</h4>
        <p>{{description}}</p>

        {% if postcard_text != '' %}
            <div class="postcardText">
                <h5>Text on postcard:</h5>
                <p>{{postcard_text}}</p>
            </div>
        {% endif %}
        <h5>Categories:</h5>
        <ul>
            {% for subject in card.dc.content.subject_list %}
             <li><a href="{% url 'postcards:browse' %}?subject={{subject}}">{{ subject }}</a></li>
            {% endfor %}
        </ul>
        {% if ark != '' %}  Permanent link for this postcard: <a href="{{ark}}">{{ark}}</a> {% endif %}
     </td>
  </tr>
</table>

{% endblock %}

templates/postcards/view_postcard_large.html
{% extends "postcards/postcard_base.html" %}

{% block page-head %}
  {{block.super}}
  {# Dublin Core metadata for this postcard #}
  {% with card.dc.content as dc %}{% include '_dc_meta.html' %}{% endwith %}
{% endblock %}

{% block page_subtitle %} {{head}} {{ card.label }}{% endblock %}

{% block content %}
<p><a href="{% url 'postcards:card' pid=card.pid %}">View full details</a></p>
<h4>{{card.label}}</h4>
<table>
  <tr>
    <td>
        <img src="{{ card.large_img_url }}"/>
    </td>  <!-- put link to 2x image here -->
  </tr>
</table>

{% endblock %}