greatWar/edc/urls.py
from django.conf.urls.defaults import *
from edc import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
	(r'^site_media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': '/home/html/greatWar/templates/'}),
	(r'^about/$', 'edc.search.views.about'),
	(r'^credits/$', 'edc.search.views.credits'),
	(r'^poetrysearch/advanced/$', 'edc.search.views.advancedSearch'),
	(r'^poetry/volume_browse/$', 'edc.search.views.volume_browse'),
	(r'^poetry/volume/(?P<volfile>\w+)/$', 'edc.search.views.volumeContent'),
	(r'^poetry/front/(?P<div_id>\w+)/$', 'edc.search.views.front_detail'),
	(r'^poetry/(?P<parent_type>\w+)/(?P<poem_id>\w+)/$', 'edc.search.views.poem_detail'),
	(r'^poetry/poem/(?P<poem_id>\w+)/$', 'edc.search.views.poem_detail'),
	(r'^$', 'edc.search.views.opening_page'),
	(r'^postcards$', 'edc.search.views.underconstruction'),
	(r'^links$', 'edc.search.views.underconstruction'),
        (r'^poetry/Poet_browse/$', 'edc.search.views.underconstruction'),
)

greatwar-django/tags/release-1.0.0/greatwar/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.conf.urls.defaults import patterns, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^greatwar/', include('greatwar.foo.urls')),
    url(r'^$', 'views.index', name="index"),
    url(r'^about/$', 'views.about', name="about"),
    url(r'^links/$', 'views.links', name="links"),
    url(r'^credits/$', 'views.credits', name="credits"),
    url(r'^poetry/', include('greatwar.poetry.urls', namespace='poetry')),
    url(r'^postcards/', include('greatwar.postcards.urls', namespace='postcards')),
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
          
)

# DISABLE THIS IN PRODUCTION
if settings.DEV_ENV:

    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            }),
    )

greatwar/poetry/urls.py
from django.conf.urls import url

from greatwar.poetry import views

urlpatterns = [
    url(r'^$', views.books, name='books'),
    url(r'^search/$', views.search, name='search'),
    url(r'^poet/$', views.poets, name="poets"),
    url(r'^poet/(?P<letter>[A-Z]*)$', views.poets_by_firstletter, name="poets-by-letter"),
    url(r'^poet/(?P<name>.*)$', views.poet_list, name="poet-list"),
    url(r'^(?P<doc_id>[^/]+)/$', views.book_toc, name="book-toc"),
    url(r'^(?P<doc_id>[^/]+)/TEI/$', views.book_xml, name="book-xml"),
    url(r'^(?P<doc_id>[^/]+)/(?P<div_id>[a-zA-Z_0-9]+)/', views.div, name="poem"),
]

greatwar/postcards/urls.py
from django.conf.urls import url
from django.views.decorators.cache import cache_page

from greatwar.postcards import views

urlpatterns = [
    url(r'^$', views.browse, name='browse'),
    url(r'^about/$', views.summary, name='index'),
    url(r'^categories/(?P<subject>.*)$', views.browse, name='browse'),
    url(r'^(?P<pid>[^/]+)$', views.view_postcard, name='card'),
    url(r'^large/(?P<pid>[^/]+)$', views.view_postcard_large, name='card-large'),
    url(r'^(?P<pid>[^/]+)/thumbnail/$', views.postcard_image, {'size': 'thumbnail'}, name='img-thumb'),
    url(r'^(?P<pid>[^/]+)/medium/$', views.postcard_image, {'size': 'medium'}, name='img-medium'),
    url(r'^(?P<pid>[^/]+)/large/$', views.postcard_image, {'size': 'large'}, name='img-large'),
    url(r'^search/$', views.search, name='search'),
]

greatwar/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from greatwar import views


admin.autodiscover()

urlpatterns = [
    # Example:
    url(r'^$', views.index, name="index"),
    url(r'^$', views.index, name="site-index"), # required by eultheme
    url(r'^about/$', views.about, name="about"),
    url(r'^links/$', views.links, name="links"),
    url(r'^credits/$', views.credits, name="credits"),
    url(r'^poetry/', include('greatwar.poetry.urls', namespace='poetry')),
    url(r'^postcards/', include('greatwar.postcards.urls', namespace='postcards')),
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # django admin, for downtime/banners
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEV_ENV:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/_dc_meta.html
 {# Dublin Core metadata in html header format - expects DublinCore as dc #}
 <link rel="schema.DC" href="http://purl.org/dc/elements/1.1/" />
 {% for el in dc.elements %}
 <meta name="DC.{{ el.name }}" content="{{ el }}" />{% endfor %}

templates/about.html
{% extends "base.html" %}
{% block pagetitle %} | About {% endblock %}

{% block content %}
<h2 class="title">About This Project</h2>
<p><i>The Great War 1914-1918</i> began as a resource for courses in World War I poetry, a topic now taught in a number of universities. The site has since grown to be of interest to anyone studying World War I.  Several years ago Woodruff Library of Emory University purchased fifty volumes of poetry written between 1914 and 1918; none of these books went into second editions, so they are now rather difficult to find except in specialized collections.  The Beck Center of Woodruff Library is putting these volumes and others, beginning with the poetry by women, on line as e-texts, thus making available an interesting collection of poetry from a time that witnessed an unparalleled outpouring of war poetry by the men fighting in the trenches, by the poets at home trying to raise the morale of the troops, and by the women who could do little else but volunteer as aids or wait anxiously at home for their sons, husbands, and lovers. The poems are the heart of the site, and readers will appreciate being able to search the poetry by volume, title, author, and even individual lines and words.</p>

<p>After beginning the project with poetry, Dr. Alice Hickcox of the Beck Center suggested that <i>The Great War 1914-1918</i> might expand to include other aspects of popular culture--which is for the most part how we would describe the poetry on this site--beginning with a collection of some 450 postcards from World War I.  With the assistance of Dr. Erika Farr and Rebecca Sutton Koeser the postcards were scanned, categorized and described to become what is, to our knowledge, one of the largest collections of World War I cards on the web. </p>

<p> How many of us would think of postcards when we study the history of the First World War? Lest these ephemeral bits of paper seem too marginal and trivial, let's put the topic of the war and postcards in its historical context. For deltiologists (a name with which we collectors attempt to dignify our hobby) the "golden age" of postcards corresponds roughly with the first decades of the twentieth century when picture-postcard collecting became a worldwide phenomenon--a mania, in fact. Richard Carline, writing in 1971, says it is difficult for us today to appreciate what cards meant to people sixty or more years ago, but during the quarter of a century that included the Great War, thousands of hobbyists sought cards to add to their collections (<i>Pictures in the Post</i>, 9).</p>

<p> In 1911 the Atlantic City Post Office sold in that single year 17,000,000 one-cent stamps, most of them destined to be stuck on postcards. At Christmas, 1909, more than 1,000,000 postcards were handled by the Baltimore Post Office, and the St. Louis Post Office cancelled 750,000 cards on a single day in that same Christmas season. The postcard mania was indeed in full swing in the first decade of the last century. Dorothy Ryan calls the number of postcards sent through the mails at the height of their popularity "staggering." In 1906 the <i>Post Card Dealer</i> reported that Germany's annual consumption was 1,161,000,000; the United States', 770,500,000; and Great Britain's, 734,500,000. Official United States Post Office figures for the year ending June 30, 1908, cite 667,777,798 postcards mailed in this country. By 1913--just a year before war was declared--the total in the United States had increased to over 868,000,000, and by this date the craze was reportedly on the decline (Picture Postcards in the United States, 1893-1918, 22).</p>

<p>A rough estimate, Richard Carline suggests, is that in 1905 about seven thousand million postcards were handled by the various postal services worldwide; his source is a magazine published especially for collectors, the September, 1905 issue of <i>Picture Postcard Magazine</i>. The war was soon to generate its share of postcards mailed back and forth from the front to home in every country.</p>

<p>This site allows the user to search the cards in a variety of ways
and demonstrates the place of the postcard in the popular culture of
the war.  The category of "nationality" shows cards from a dozen
countries, the "military" selection depicts actual scenes and photos
of the trenches and the destruction caused by the war.  The cards in
the "home front" section have many sentimental romantic and religious
cards meant to cheer the men at the front and comfort loved ones at
home. We are still in the process of editing the descriptions of the
cards, but browsing through the categories reveals the variety of
cards and the feelings they attempted to express.  Some of the most
interesting cards are known as "silks," carefully embroidered cards
that brought a small income to the French women who produced them.
They sold for a few francs each, really only a few cents, but I have
never seen one that was sent as a card; they were too exquisitely
embroidered to trust to the mail without an envelope to protect them.
Like most postcards, these silks injected a bit of normalcy in an
otherwise increasingly insane war.</p>

   <div class="sig">-- Harry Rusche</font></div>


{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
   <title>The Great War {% block pagetitle %} PAGE TITLE {% endblock %} </title>
   <link rel="icon" type="image/jpeg" href="{% static 'images/favicon.jpg' %}">
   <link rel="stylesheet" type="text/css" href="{% static 'css/site.css' %}"/>

  {% block page-head %}
  {% endblock %}
</head>

<body>

  {% block mx_banner %}
      {% if banner %}
         {% include 'mx/banner.html' %}
      {% endif %}
  {% endblock %}

 <div class="topimage"><img src="{% static 'images/topbanner.jpg' %}" alt="The Great War" width='800' height='90' border='0'/></div>

<table class="indexlinks">
<tr>
     <td><a href='{% url 'index' %}'>Home</a></td>
     <td class="separator">&bull;</td>
     <td><a href="{% url 'postcards:index' %}">Postcards</a></td>
     <td class="separator">&bull;</td>
     <td><a href="{% url 'poetry:books' %}">Poetry</a></td>
     <td class="separator">&bull;</td>
     <td><a href="{% url 'links' %}">Links</a></td>
     <td class="separator">&bull;</td>
     <td><a href="{% url 'about' %}">About the Site</a></td>
     <td class="separator">&bull;</td>
     <td><a href="{% url 'credits' %}">Credits</a></td>
</tr>

</table>
        <hr align="left"/>
{% block page_title %}{% endblock %}
<div class="sidebar">

<div class="nav">
{% block section_nav %}
 <h3>Navigation</h3>
  <p>Poetry:
   <a href="{% url 'poetry:books' %}">Browse Volumes</a><br/>
   <a href="{% url 'poetry:poets' %}">Browse by Poet</a><br/>
   <a href="{% url 'poetry:search' %}">Advanced Search</a>
  </p>
   <p>Postcards:
   <a href="{% url 'postcards:browse' %}">Browse Postcards</a><br>
   <a href="{% url 'postcards:index' %}">Postcards Home</a><br>
   <a href="{% url 'postcards:search' %}">Advanced Search</a>
  </p>
{% endblock %}
</div>

<div class='search'>
<h3>Search the poetry</h3>
<form method="get" action="{% url 'poetry:search' %}">
    <table>
    {# { search.as_table } #}
    </table>

<input type='text' name='keyword' size='15'/>
<input type='submit' value='Go'/>

</form>
<h3>Search the postcards</h3>
    <form method="get" action="{% url 'postcards:search' %}">
<input type='text' name='description' size='15'/>
<input type='submit' value='Go'/>

</form>

</div>
</div>

<div class="content">

{% block postcard %}
{% endblock %}
{% block content %}
{% endblock %}

</div>

{% if querytime %} <p>Query took {{ querytime }}ms </p> {% endif %}

<div class="footer">

   <table width="500" border="0" align="center">
     <tr>
        <td><a href="http://beck.library.emory.edu/">The Beck Center</a></td>
        <td><a href="http://www.library.emory.edu/">EUCLID</a></td>
        <td><a href="http://www.library.emory.edu/IG/">Information Gateway</a></td>
        <td><a href="http://www.emory.edu/LIBRARIES/">General Library</a></td>
        <td><a href="http://www.emory.edu/">Emory University</a></td>
      </tr>
    </table>


<p class="copy">{{ SW_VERSION }} | &copy; 2004 Emory University</p>
</div>


</body>
</html>

templates/credits.html
{% extends "base.html" %}
{% block pagetitle %} | Credits{% endblock %}
{% block content %}
<h2>Credits</h2>
<h3>The Editorial Board</h3>
<p class="credits">Harry Rusche, Arthur M. Blank Distinguished Teaching Professor of English<br/>
Alice Hickcox, Electronic Text Specialist, Beck Center<br/>
Rebecca Sutton Koeser, Woodruff Fellow, Beck Center<br/>
Charles Spornick, Coordinator, Beck Center</p>

<h3>Scanning and Encoding Postcards</h3>
<p class="credits">Amy Parker<br/>
Kate Schelbe</p>

<h3>Scanning, Proofreading, and Encoding Poetry</h3>
<p class="credits">Erika Farr<br/>
Alden Mahler<br/>
Josh Klehr<br/>
Matt Gunning<br/>
Shruthi Vissa<br/>
Tyler Kellerman</p>


<h3>Programming Support</h3>
<p class="credits">Julia Leon, Academic Technology Group, Information Technology<br/>
Rebecca Sutton Koeser, Senior Software Engineer, Digital Systems and Programs</p>
<p class="credits">For the 2010 site revision, thanks must go to the
entire Digital Systems and Programs Software Engineering team (Scott
Turnbull, Ben Ranker, Rebecca Sutton Koeser, Sari Connard, Alex
Thomas, and Steven Anderson, who developed the Django framework for
the display of TEI with eXist and the Fedora storage and display for
the postcards, and generously supported the coding of this site.</p>

<h3>Original Site Design</h3>
<p class="credits">Lieanna Lieanna</p>
<!-- so footer will not cover last name -->
<p>&nbsp;</p>
{% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
    <link rel="icon" type="image/jpeg" href="{% static 'images/favicon.jpg' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/site.css' %}">
<title>The Great War</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css">
a:link	  { color: #000000; }
a:active  { color: #687c54; }
a:visited { color: #800000; }
a:hover   { background-color: #ededed; }
body { text-align: center; }
</style>
  <link rel="schema.DC" href="http://purl.org/dc/elements/1.1/"/>
  <link rel="schema.DCTERMS" href="http://purl.org/dc/terms/"/>
  <meta name="DC.title" content="The Great War, 1914-1918"/>
  <meta name="DC.creator" content="Lewis H. Beck Center for Electronic Collections &amp; Services"/>
  <meta name="DC.publisher" content="Lewis H. Beck Center for Electronic Collections &amp;  Services"/>
  <meta name="DC.subject" content="Poetry"/>
  <meta name="DC.subject" content="Postcards"/>
  <meta name="DC.subject" content="World War I"/>
  <meta name="DC.subject" content="World War, 1914-1918"/>
  <meta name="DC.subject" content="Emory University"/>
  <meta name="DC.description" content="Poetry written between 1914 and 1918 from 50 scarce volumes acquired by Emory University and a collection of some 450 postcards from World War I."/>
  <meta name="DC.type" scheme="DCTERMS.DCMIType" content="text"/>
  <meta name="DC.format" scheme="DCTERMS.IMT" content="text/html"/>
  <meta name="DC.identifier" content="http://cti.library.emory.edu/greatwar/"/>
  <meta name="DC.date" content="2004-10-01"/>
</head>

<body bgcolor="#5d6a50">

  {% block mx_banner %}
      {% if banner %}
         {% include 'mx/banner.html' %}
      {% endif %}
  {% endblock %}


<div class="index">
<p>
<img src="{% static 'images/front.jpg' %}" width="600" height="400" border="0"
  alt="The Great War">
</p>

<table class="indexlinks">
<tr>
<td><a href="{% url 'about' %}">About the Site</a></td>
<td class="separator">&bull;</td>
<td><a href="{% url 'postcards:index' %}">Postcards</a></td>
<td class="separator">&bull;</td>
<td><a href="{% url 'poetry:books' %}">Poetry</a></td>
<td class="separator">&bull;</td>
<td><a href="{% url 'links' %}">Links</a></td>
</tr>

</table>
</div>
<div class="footer">

   <table width="500" border="0" align="center">
     <tr>
        <td><a href="http://beck.library.emory.edu/">The Beck Center</a></td>
        <td><a href="http://www.library.emory.edu/">EUCLID</a></td>
        <td><a href="http://discovere.emory.edu">DiscoverE</a></td>
        <td><a href="http://web.library.emory.edu/">Emory Main Library</a></td>
        <td><a href="http://www.emory.edu/">Emory University</a></td>
      </tr>
    </table>


<p class="copy">&copy; 2004 Emory University</p>
</div>


</body>
</html>

templates/links.html
{% extends "base.html" %}
{% block pagetitle %} | Links{% endblock %}

{% block content %}
<h2>Links</h2>
<h2>Useful resources about the Great War.</h2>
<p class="link">WWI:Links to other WWI sites<br/>
<a
href="http://wwi.lib.byu.edu/index.php/Links_to_Other_WWI_Sites">http://wwi.lib.byu.edu/index.php/Links_to_Other_WWI_Sites</a>,
a rich resource of links to many sites about World War One.</p>
<hr/>
<p class="link">The Wikipedia article<br/>
<a href="http://en.wikipedia.org/wiki/World_War_I">http://en.wikipedia.org/wiki/World_War_I</a></p>
<hr/>
<p class="link">firstworldwar.com<br/>
<a href="http://www.firstworldwar.com/index.htm">http://www.firstworldwar.com/index.htm</a>, a multimedia site about the Great War.</p>
<hr/>
<p class="link">A Guide to WW1 Battlefields and History of the First World War<br/>
<a href="http://www.greatwar.co.uk/">http://www.greatwar.co.uk/</a>
This site provides an overview of the First World War battlefields on
the Western Front by showing you where they are and what you can see
today.
</p>
<hr/>
<p class="link">The First World War Poetry Digital Archive<br/>
<a href="http://www.oucs.ox.ac.uk/ww1lit">http://www.oucs.ox.ac.uk/ww1lit</a>
The First World War Poetry Digital Archive is an online repository of over 7000 items of text, images, audio, and video for teaching, learning, and research.<br/></p>
<p class="link">The Great War Archive<br/>
<a href="http://www.oucs.ox.ac.uk/ww1lit/gwa">http://www.oucs.ox.ac.uk/ww1lit/gwa</a>
The Great War Archive contains over 6,500 items contributed by the general public between March and June 2008. Every item originates from, or relates to, someone's experience of the First World War, either abroad or at home. Contributions were received via a special website and also through a series of open days at libraries and museums throughout the country.
</p>
<hr/>

<!-- <p class="link"> -->
<!-- <a href="http://www.spartacus.schoolnet.co.uk/FWW.htm">http://www.spartacus.schoolnet.co.uk/FWW.htm</a> -->
<!-- This British site has brief history articles. -->
<!-- </p> -->
<!-- <hr/> -->
<p class="link">The World War I
Document Archive<br/>
<a href="http://wwi.lib.byu.edu/index.php/Main_Page">http://wwi.lib.byu.edu/index.php/Main_Page</a>
Links to primary documents about WWI.
</p>
<hr/>
<p class="link">BBC-History-World War One<br/>
<a href="http://www.bbc.co.uk/history/worldwars/wwone/">http://www.bbc.co.uk/history/worldwars/wwone/</a>
Multimedia resources about the war.</p>
<hr/>
<p class="link">Propaganda Postcards of World War 1<br/>
<a href="http://www.ww1-propaganda-cards.com/">http://www.ww1-propaganda-cards.com/</a>
More postcards, with context and background of artists.</p>
<hr/>
<p class="link">Art of the First World War<br/>
<a href="http://www.art-ww1.com/">http://www.art-ww1.com/</a>
A collaboration of museums for the 80th anniversary of the Armistice.</p>
<hr/>
<p class="link">The Great War | PBS<br/>
<a href="http://www.pbs.org/greatwar/">http://www.pbs.org/greatwar/</a>
A history of the war by public television.</p>
<hr/>
<p class="link">In Flanders Field Museum<br/>
<a href="http://www.inflandersfields.be/">http://www.inflandersfields.be/</a>
This site contains much information about the Great War in Belgium.
</p>
<hr/>
{% endblock %}